execute @s[family=solrrmissile,scores={solrrangle=0}] ~ ~ ~ tp @s ~~~ 0 0
execute @s[family=solrrmissile,scores={solrrangle=1}] ~ ~ ~ tp @s ~~~ -5.625 0
execute @s[family=solrrmissile,scores={solrrangle=2}] ~ ~ ~ tp @s ~~~ -11.25 0
execute @s[family=solrrmissile,scores={solrrangle=2}] ~ ~ ~ tp @s ~~~ -16.875 0
execute @s[family=solrrmissile,scores={solrrangle=3}] ~ ~ ~ tp @s ~~~ -22.5 0
execute @s[family=solrrmissile,scores={solrrangle=4}] ~ ~ ~ tp @s ~~~ -28.125 0
execute @s[family=solrrmissile,scores={solrrangle=5}] ~ ~ ~ tp @s ~~~ -33.75 0
execute @s[family=solrrmissile,scores={solrrangle=6}] ~ ~ ~ tp @s ~~~ -39.375 0
execute @s[family=solrrmissile,scores={solrrangle=7}] ~ ~ ~ tp @s ~~~ -45 0
execute @s[family=solrrmissile,scores={solrrangle=8}] ~ ~ ~ tp @s ~~~ -50.625 0
execute @s[family=solrrmissile,scores={solrrangle=9}] ~ ~ ~ tp @s ~~~ -56.25 0
execute @s[family=solrrmissile,scores={solrrangle=10}] ~ ~ ~ tp @s ~~~ -61.875 0
execute @s[family=solrrmissile,scores={solrrangle=11}] ~ ~ ~ tp @s ~~~ -67.5 0
execute @s[family=solrrmissile,scores={solrrangle=12}] ~ ~ ~ tp @s ~~~ -73.125 0
execute @s[family=solrrmissile,scores={solrrangle=13}] ~ ~ ~ tp @s ~~~ -78.75 0
execute @s[family=solrrmissile,scores={solrrangle=14}] ~ ~ ~ tp @s ~~~ -84.375 0
execute @s[family=solrrmissile,scores={solrrangle=15}] ~ ~ ~ tp @s ~~~ -90 0
execute @s[family=solrrmissile,scores={solrrangle=16}] ~ ~ ~ tp @s ~~~ -95.625 0
execute @s[family=solrrmissile,scores={solrrangle=17}] ~ ~ ~ tp @s ~~~ -101.25 0
execute @s[family=solrrmissile,scores={solrrangle=18}] ~ ~ ~ tp @s ~~~ -106.875 0
execute @s[family=solrrmissile,scores={solrrangle=19}] ~ ~ ~ tp @s ~~~ -112.5 0
execute @s[family=solrrmissile,scores={solrrangle=20}] ~ ~ ~ tp @s ~~~ -118.125 0
execute @s[family=solrrmissile,scores={solrrangle=21}] ~ ~ ~ tp @s ~~~ -123.75 0
execute @s[family=solrrmissile,scores={solrrangle=22}] ~ ~ ~ tp @s ~~~ -129.375 0
execute @s[family=solrrmissile,scores={solrrangle=23}] ~ ~ ~ tp @s ~~~ -135 0
execute @s[family=solrrmissile,scores={solrrangle=24}] ~ ~ ~ tp @s ~~~ -140.625 0
execute @s[family=solrrmissile,scores={solrrangle=25}] ~ ~ ~ tp @s ~~~ -146.25 0
execute @s[family=solrrmissile,scores={solrrangle=26}] ~ ~ ~ tp @s ~~~ -151.875 0
execute @s[family=solrrmissile,scores={solrrangle=27}] ~ ~ ~ tp @s ~~~ -157.5 0
execute @s[family=solrrmissile,scores={solrrangle=28}] ~ ~ ~ tp @s ~~~ -163.125 0
execute @s[family=solrrmissile,scores={solrrangle=29}] ~ ~ ~ tp @s ~~~ -168.75 0
execute @s[family=solrrmissile,scores={solrrangle=30}] ~ ~ ~ tp @s ~~~ -174.375 0
execute @s[family=solrrmissile,scores={solrrangle=31}] ~ ~ ~ tp @s ~~~ -180 0
execute @s[family=solrrmissile,scores={solrrangle=32}] ~ ~ ~ tp @s ~~~ -185.625 0
execute @s[family=solrrmissile,scores={solrrangle=33}] ~ ~ ~ tp @s ~~~ -191.25 0
execute @s[family=solrrmissile,scores={solrrangle=34}] ~ ~ ~ tp @s ~~~ -196.875 0
execute @s[family=solrrmissile,scores={solrrangle=35}] ~ ~ ~ tp @s ~~~ -202.5 0
execute @s[family=solrrmissile,scores={solrrangle=36}] ~ ~ ~ tp @s ~~~ -208.125 0
execute @s[family=solrrmissile,scores={solrrangle=37}] ~ ~ ~ tp @s ~~~ -213.75 0
execute @s[family=solrrmissile,scores={solrrangle=38}] ~ ~ ~ tp @s ~~~ -219.375 0
execute @s[family=solrrmissile,scores={solrrangle=39}] ~ ~ ~ tp @s ~~~ -225 0
execute @s[family=solrrmissile,scores={solrrangle=40}] ~ ~ ~ tp @s ~~~ -230.625 0
execute @s[family=solrrmissile,scores={solrrangle=41}] ~ ~ ~ tp @s ~~~ -236.25 0
execute @s[family=solrrmissile,scores={solrrangle=42}] ~ ~ ~ tp @s ~~~ -241.875 0
execute @s[family=solrrmissile,scores={solrrangle=43}] ~ ~ ~ tp @s ~~~ -247.5 0
execute @s[family=solrrmissile,scores={solrrangle=44}] ~ ~ ~ tp @s ~~~ -253.125 0
execute @s[family=solrrmissile,scores={solrrangle=45}] ~ ~ ~ tp @s ~~~ -258.75 0
execute @s[family=solrrmissile,scores={solrrangle=46}] ~ ~ ~ tp @s ~~~ -264.375 0
execute @s[family=solrrmissile,scores={solrrangle=47}] ~ ~ ~ tp @s ~~~ -270 0
execute @s[family=solrrmissile,scores={solrrangle=48}] ~ ~ ~ tp @s ~~~ -275.625 0
execute @s[family=solrrmissile,scores={solrrangle=49}] ~ ~ ~ tp @s ~~~ -281.25 0
execute @s[family=solrrmissile,scores={solrrangle=50}] ~ ~ ~ tp @s ~~~ -286.875 0
execute @s[family=solrrmissile,scores={solrrangle=51}] ~ ~ ~ tp @s ~~~ -292.5 0
execute @s[family=solrrmissile,scores={solrrangle=52}] ~ ~ ~ tp @s ~~~ -298.125 0
execute @s[family=solrrmissile,scores={solrrangle=53}] ~ ~ ~ tp @s ~~~ -303.75 0
execute @s[family=solrrmissile,scores={solrrangle=54}] ~ ~ ~ tp @s ~~~ -309.375 0
execute @s[family=solrrmissile,scores={solrrangle=55}] ~ ~ ~ tp @s ~~~ -315 0
execute @s[family=solrrmissile,scores={solrrangle=56}] ~ ~ ~ tp @s ~~~ -320.625 0
execute @s[family=solrrmissile,scores={solrrangle=57}] ~ ~ ~ tp @s ~~~ -326.25 0
execute @s[family=solrrmissile,scores={solrrangle=58}] ~ ~ ~ tp @s ~~~ -331.875 0
execute @s[family=solrrmissile,scores={solrrangle=59}] ~ ~ ~ tp @s ~~~ -337.5 0
execute @s[family=solrrmissile,scores={solrrangle=60}] ~ ~ ~ tp @s ~~~ -343.125 0
execute @s[family=solrrmissile,scores={solrrangle=61}] ~ ~ ~ tp @s ~~~ -348.75 0
execute @s[family=solrrmissile,scores={solrrangle=62}] ~ ~ ~ tp @s ~~~ -354.375 0